### ISSUE TITLE
Compile issue.

### ISSUE THREAD

**Issue by FreeBSD-pzn** [JonathanBelanger/DECaxp#1]
Hello Jonathan!
I am trying to compile DECaxp under FreeBSD. I 've got:
In file included from /emulator/Alpha/prg/DECaxp/src/comutl/AXP_VirtualDisk.c:32:0:
/emulator/Alpha/prg/DECaxp/src/comutl/AXP_VHDX.h:265:5: error: unknown type name 'AXP_BLOCK_DSC'
     AXP_BLOCK_DSC header;
     ^~~~~~~~~~~~~
/emulator/Alpha/prg/DECaxp/src/comutl/AXP_VirtualDisk.c: In function 'AXP_VHD_Open':
/emulator/Alpha/prg/DECaxp/src/comutl/AXP_VirtualDisk.c:289:12: warning: implicit declaration of function '_AXP_RAW_Open' [-Wimplicit-function-declaration]
   retVal = _AXP_RAW_Open(
            ^~~~~~~~~~~~~
/emulator/Alpha/prg/DECaxp/src/comutl/AXP_VirtualDisk.c: In function 'AXP_VHD_CloseHandle':
/emulator/Alpha/prg/DECaxp/src/comutl/AXP_VirtualDisk.c:338:22: error: request for member 'type' in something not a structure or union
     if ((vhdx->header.type == AXP_VHDX_BLK) &&
                      ^
/emulator/Alpha/prg/DECaxp/src/comutl/AXP_VirtualDisk.c:339:15: error: request for member 'size' in something not a structure or union
  (vhdx->header.size == sizeof(AXP_VHDX_Handle)))
               ^

**Comment by FreeBSD-pzn** [comment]
Hi!
Today I have compiled files DECaxp in the FreeBSD 11.2, except:
 ./app/DECaxp.c;
 ./comutl/AXP_Blocks.c, ./comutl/AXP_Telnet.c, ./comutl/AXP_VHD_Utility.c;
 ./cpu/AXP_21264_CPU.c;
 ./system/AXP_DS12887A_TOYClock.c;
 ./tst/AXP_21264_Prediction_Test.c, ./tst/AXP_Telnet_Test.c

To compile them I need a help ...

To compile files I needed edited some files:
 ./comutl/AXP_Blocks.c, ./comutl/AXP_Blocks.h, ./comutl/AXP_Telnet.h,
 ./comutl/AXP_GUID.h, ./comutl/AXP_Utility.c, ./comutl/AXP_VHD_Utility.h;
 ./cpu/AXP_21264_CPU.h, ./cpu/AXP_21264_Ebox_PALfunctions.c;
 ./system/AXP_21274_System.h, ./system/AXP_DS12887A_TOYClock.c.

and Makefile.

~Oleg

**Comment by FreeBSD-pzn** [comment]
Hi!
When I have compiled ../cpu/AXP_21264_CPU.c I have got an error:
********
gcc -c  -I/emulator/Alpha/prg/_DECaxp/src/comutl/  -I/emulator/Alpha/prg/_DECaxp/src/cpu/  -I/emulator/Alpha/prg/_DECaxp/src/system/ -I/usr/local/include/libxml2/ -I/usr/local/include/ -I/usr/include/ -m64 -std=gnu99 -Wall -pthread -D_AXP_COMPILER_PRESENT_ -g -O0 -DDEBUG -o /emulator/Alpha/prg/_DECaxp/bin/AXP_21264_CPU.o /emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c: In function 'AXP_21264_AllocateCPU':
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c:64:11: warning: implicit declaration of function 'AXP_Allocate_Block' [-Wimplicit-function-declaration]
     cpu = AXP_Allocate_Block(AXP_21264_CPU_BLK);
           ^~~~~~~~~~~~~~~~~~
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c:64:30: error: 'AXP_21264_CPU_BLK' undeclared (first use in this function)
     cpu = AXP_Allocate_Block(AXP_21264_CPU_BLK);
                              ^~~~~~~~~~~~~~~~~
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c:64:30: note: each undeclared identifier is reported only once for each function it appears in
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c:255:6: warning: implicit declaration of function 'AXP_Deallocate_Block' [-Wimplicit-function-declaration]
      AXP_Deallocate_Block((AXP_BLOCK_DSC *) cpu);
      ^~~~~~~~~~~~~~~~~~~~
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c:255:28: error: 'AXP_BLOCK_DSC' undeclared (first use in this function)
      AXP_Deallocate_Block((AXP_BLOCK_DSC *) cpu);
                            ^~~~~~~~~~~~~
/emulator/Alpha/prg/_DECaxp/src/cpu/AXP_21264_CPU.c:255:43: error: expected expression before ')' token
      AXP_Deallocate_Block((AXP_BLOCK_DSC *) cpu);
*****
Well, I was trying to found where has beed declared AXP_21264_CPU_BLK and AXP_BLOCK_DSC, but I did not found.

**Comment by JonathanBelanger** [comment]
Hi Oleg,

AXP_21264_CPU_BLK and AXP_BLOCK_DSC are defined in comutl/AXP_Blocks.h.  Also, AXP_BLOCK_DSC is no longer required at the top of the allocation blocks.  I made a change to how memory is allocated.  All memory allocations go through AXP_Blocks.c (AXP_Allocate_Block function).  This function has change the first parameter from an enumerated value to a signed integer.  If the signed integer is negative, then a block of bytes is being requested.  The number of bytes is the absolute value of this signed value.  If this parameter is greater than zero, then it is a specific type of block (which has a sizeof value).

Also, the allocated blocks no longer need a header record defined within the block being allocated.  I have moved this information outside of the allocated block and have also added a tail section.  This header and tail section contain all the information needed to describe the block for the allocation/deallocation functions.  Also, if a second parameter is supplied on the AXP_Allocate_Block, then a reallocate for a larger block is being requested (this only works for a block of bytes, as described above).  So, what this all means is that when allocating blocks, additional bytes will be added to the beginning and end of the the block for this header/tail information.  This header/tail information will be invisible to the caller of the Allocate and Deallocate function (this allows for the block of bytes functionality).

Also, the parameter on the AXP_Deallocate_Block has been changed to a void *, so there is no need to cast anymore.  It is not needed, since the information this function needs is in the header and tail.

This past weekend, I performed a compile to remove compiler errors, so these should not be happening any more.  Also, since finishing up the CPU side of the emulation, I have been doing quite a bit of refactoring.  I have also started a number of things that are not yet completed.  I have the TOY clock working, the start of the virtual hard disk (you can create one, but not yet open it), and starting the networking code.  None of these currently has anyway to interface with and work with the system.  Also, I have redesigned the Bcache, but not yet implemented it.  The Bcache is going to be shared across all processors.  This will eliminate the need to utilize probes and the like through the CPU-System interface.  It should make things perform better, but it will also adjust some of the timings.  We'll have to see if this design will work the way I want it to.

Please note, that the copyright on these files is mine and not the GNU open source one.  That does not mean that I will not allow others to use it.  It does mean that I retain all rights to the software in its entirely.  I will entertain code changes from others, but reserve the right to reject them or alter them to be consistent with the format and style of all the other code.

~Jon.

**Comment by JonathanBelanger** [comment]
I just updated the files and they built cleanly on Cygwin.
