### ISSUE TITLE
telnet login

### ISSUE THREAD

**Issue by willemsk** [JonathanBelanger/DECaxp#11]
Hi Jonathan,

Thank you for the titanic effort you have already put into this project, it already is an amazing piece of work!

I managed to successfully compile your code and run a dummy config file with the DECaxp binary, but it idles at 
`%DECAXP-I-START, The Digital Alpha AXP 21264 CPU Emulator is starting.`
and it doesn't seem to start a telnet session (it also isn't listening on any ports). Is this normal behavior, or am I missing something?

Cheers,
Kherim

**Comment by JonathanBelanger** [comment]
I there is a `DECaxp_Initial_Configuration.xml` file in the data files area.  Did you use and update that, or did you start with a clean sheet.  If the latter, try looking at the supplied file and make sure everything is as it seems.  Also, DECaxp will listen on port 108, and not the usual default port.

If you want, you can post the config file you have and I can look it over.

Also, it has been a while since I worked on DECaxp.  The project is not dead, I'm just taking a hiatus and working on some other things (like a LLVM Bliss compiler).  So, please don't be frustrated by the slowness of my responses.

**Comment by JonathanBelanger** [comment]
Hi Kherim,

I just moved this project over to GitLab.  GitHub wanted to start charging me, so I decided it was time to move.

Please subscribe over there, as this issue should have been migrated.

Jon.
