### ISSUE TITLE
WinPCAP library issue

### ISSUE THREAD

**Issue by TheFausap** [JonathanBelanger/DECaxp#2]
Hello Jonathan,

this is a wonderful project and also the name is perfect. Digital is Digital, not to be mixed with Compaq or, even worse, HP.
I'm trying to compile under cygwin64, but I'm stuck with winpcap. I downloaded the development kit, but I suppose the libpacket.a anche libwpcap.a are only 32bit version, but at the end, during the link phase, ld throws a lot of errors about incompatible library (libwpcap.a)

I noticed, in the Makefile, the LIBS variable is missing of libiconv and libwpcap, is this intended?

Do you have a 64bit version of that library (wpcap), or do you suggest I can install cygwin32 ?

thanks,
Fausto

**Comment by JonathanBelanger** [comment]
No, I'm using cygwin64.  winpcap is an odd one.  Because some portion of it needs to run down in the kernel, it actually has to straddle cygwin and Windows.  At a look at the following link to get WinPcap installed so that Cygwin64 can use it:  [help installing libpcap on cygwin](https://stackoverflow.com/questions/2396251/help-installing-libpcap-on-cygwin)

Let me know how it goes.

Right now, I'm writing a portable version of SDL (I call it OpenSDL :)).  I want to use this to better define my structures.

~Jon.

**Comment by TheFausap** [comment]
Hello Jonathan,

I checked the link and now I'm able to compile the example in wpdpack archive.
The problem, at the moment, is that the two libraries shipped withing wpdpack (libpacket and libwpcap) are only 32bits library. Unfortunately in the original package, there's no 64bit version of those libraries (there're only two .lib files in the 64bit folder).

I can try to compile from source winpcap, and let you know.

I imagine decaxp is a 64bit application, so we need 64bit libraries too.

**Comment by TheFausap** [comment]
Hello Jonathan,

is it possible to compile everything under Linux ?
I have some problems with PCAP, but I'm not sure if the code is only compatible with winpcap. 

thanks
Fausto
